strict-sigcheck = false

[Instagram]
enabled = true
brand = "piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
arch = "arm64-v8a"
patcher-args = "-e 'Theme' -Oamoled=true"

[Instagram.patches]
"github:crimera/piko" = []
